# Generated by Django 4.1.4 on 2023-01-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_categotia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categotia',
            new_name='Category',
        ),
    ]
