# Generated by Django 4.1.4 on 2023-02-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0005_figures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Figures',
        ),
    ]
