# Generated by Django 4.1.4 on 2023-02-07 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0006_delete_figures'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.CreateModel(
            name='ImageProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='products')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcoder.products')),
            ],
        ),
    ]
