# Generated by Django 4.1.4 on 2023-02-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0007_products_image_imageproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproducts',
            old_name='Products',
            new_name='producto',
        ),
    ]
